### ISSUE TITLE
Error Modules

### ISSUE THREAD

**Issue by xtpj** [zentir0g/fedded-selfbot#1]
Error here : 

Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\xxxx\fedded.py", line 30, in <module>
    bot = commands.Bot(command_prefix=prefix, self_bot=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by zentir0g** [comment]
uninstall discord.py from ur VPS or computer before running.
